### ISSUE TITLE
Getting ES Module errors all of a sudden

### ISSUE THREAD

**Issue by jwld** [evansiroky/node-geo-tz#182]
Encountered after I deleted `yarn.lock` and did a fresh install on my project.

```
Error [ERR_REQUIRE_ESM]: require() of ES Module blah/node_modules/point-in-polygon-hao/dist/pointInPolygon.mjs not supported.
Instead change the require of blah/node_modules/point-in-polygon-hao/dist/pointInPolygon.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (blah/node_modules/@turf/boolean-point-in-polygon/dist/cjs/index.cjs:2:26)
    at Object.<anonymous> (blah/node_modules/geo-tz/dist/find-1970.js:1:61)
```

Looks like https://github.com/rowanwins/point-in-polygon-hao was updated a few hours ago which has busted this.

**Comment by evansiroky** [comment]
It seems like this has been fixed in v1.2.3 of [point-in-polygon-hao](https://github.com/rowanwins/point-in-polygon-hao). Please re-open if this is not the case.
