### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'call')

### ISSUE THREAD

**Issue by mohanedmashaly21** [evansiroky/node-geo-tz#184]
## Discussion

TypeError: Cannot read properties of undefined (reading 'call')
    at Object.booleanPointInPolygon (//node_modules/@turf/boolean-point-in-polygon/index.ts:57:28)
    at /node_modules/@nestjs/core/router/router-execution-context.js:38:29

**Comment by evansiroky** [comment]
Duplicate of #182?
