### ISSUE TITLE
Error on some locations

### ISSUE THREAD

**Issue by niallel** [evansiroky/node-geo-tz#32]
Hi,

I'm running the following:

`var geoTz = require('geo-tz');

var name = geoTz.tz(47.650499, -122.350070);
console.log(name);

var name2 = geoTz.tz(-34.9286, 138.6);
console.log(name2);

var name3 = geoTz.tz(53.539677, -2.714855);
console.log(name3);
`

Which returns correctly for the first two location, LA and Adelaide, but not for the third which is where I live. I'm getting the following:

`America/Los_Angeles
Australia/Adelaide
fs.js:634
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './data/b/a/d/d/a/a/d/geo.buf'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at Object.getTimezone [as tz] (/Users/niall/Desktop/geo-timezone/node_modules/geo-tz/lib/find.js:88:29)
    at Object.<anonymous> (/Users/niall/Desktop/geo-timezone/app.js:9:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)`

Any ideas?

**Comment by evansiroky** [comment]
looks like a PR is already being opened to fix this in #31

**Comment by niallel** [comment]
Brilliant, many thanks.
