### ISSUE TITLE
OSM timezone data contains LineStrings and GeometryGroups with LineStrings which breaks find.

### ISSUE THREAD

**Issue by despairblue** [evansiroky/node-geo-tz#90]
The data from OSM is not perfect so it contains sometimes nonsensical data like LineStrings. If it returns a LineString this `find` will through when we're trying to find out if a certain point is in a LineString:

```
> geoTz(-86, 0)
TypeError: Cannot read property '0' of undefined
    at inRing (/home/despairblue/git/node-geo-tz/node_modules/@turf/boolean-point-in-polygon/index.js:85:16)
    at booleanPointInPolygon (/home/despairblue/git/node-geo-tz/node_modules/@turf/boolean-point-in-polygon/index.js:56:13)
    at isPointinFeature (/home/despairblue/git/node-geo-tz/lib/find.js:187:13)
    at getTimezone (/home/despairblue/git/node-geo-tz/lib/find.js:197:13)
```

The data also contains GeometryCollections which the "@turf/boolean-point-in-polygon" also does not seem to handle well:

```
> geoTz(52.031192, 178.913872)
TypeError: Cannot read property 'length' of undefined
    at booleanPointInPolygon (/home/despairblue/git/node-geo-tz/node_modules/@turf/boolean-point-in-polygon/index.js:54:31)
    at isPointinFeature (/home/despairblue/git/node-geo-tz/lib/find.js:187:13)
    at getTimezone (/home/despairblue/git/node-geo-tz/lib/find.js:197:13)
```

I already have a fix for this. PR comes soon.

**Comment by evansiroky** [comment]
Thanks for this report. That's not good that there are non-polygon features in the lookup data. I appreciate the effort of #91, but I think that the source of the odd data is not from the OSM data (it's actually data derived from OSM via the [timezone-boundary-builder](https://github.com/evansiroky/timezone-boundary-builder) project), rather it's from the data update script within this library.

It does not look like there are any LineString features in the output from [timezone-boundary-builder](https://github.com/evansiroky/timezone-boundary-builder). Therefore, I think a better fix for this would be to make sure that only Polygons and MultiPolygons are included within the updated data output of this library. Specifically, this function could be modified to normalize the resulting lookup data: https://github.com/evansiroky/node-geo-tz/blob/217ef2ef380c8b3b1a670aa3becf9b8e89a60385/lib/geo-index.js#L86-L112
